namespace: fleet-mc-helm-example
targetCustomizations:
- name: ec2
  helm:
    values:
      replication: false
  clusterGroup: ec2-clusters

- name: eks
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterGroup: 	eks-clusters
